apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: default
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
data:
  # root 패스워드: flink123!
  root-password: ZmxpbmsxMjMh
  # 사용자 패스워드: flink123!
  password: ZmxpbmsxMjMh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "flink_db"
        - name: MYSQL_USER
          value: "flink_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        volumeMounts:
        - name: mariadb-config
          mountPath: /etc/mysql/conf.d
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-config
        configMap:
          name: mariadb-config
      - name: mariadb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
