# Flink RBAC (Role-Based Access Control) 설정
# Flink ServiceAccount가 필요한 Kubernetes 리소스에 접근할 수 있도록 권한을 부여합니다.
# - Role: pods, configmaps, deployments, flinkdeployments에 대한 권한 정의
# - RoleBinding: flink-sa ServiceAccount에 Role을 연결

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.0.1
  namespace: flink-busan
  name: flink-role
rules:
# Pods와 ConfigMaps에 대한 모든 권한 (생성, 수정, 삭제 등)
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  - endpoints
  verbs:
  - '*'
# Deployments에 대한 모든 권한
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
# FlinkDeployment CRD에 대한 권한 (Flink 클러스터 관리)
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding: flink-sa ServiceAccount에 flink-role을 연결
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: flink-busan
subjects:
  - kind: ServiceAccount
    name: flink-sa
    namespace: flink-busan
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io