# Flink SQL Gateway 배포 설정
# SQL Gateway는 REST API를 통해 Flink SQL 작업을 제출하고 관리할 수 있게 해주는 서비스입니다.
# ConfigMap, Deployment, Service를 포함합니다.

# SQL Gateway 설정을 담는 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-sql-gateway-config-20
  namespace: flink-busan
data:
  # 이 파일은 SQL Gateway Pod에 마운트됩니다.
  config.yaml: |+
    # =================================================================
    # Flink SQL Gateway 관련 설정
    # =================================================================
    # 세션 타임아웃 설정 (예: 1시간 동안 활동이 없으면 세션 종료)
    sql-gateway.session.idle-timeout: 1h
    # 세션 상태를 주기적으로 체크하는 간격
    sql-gateway.session.check-interval: 1m
    # =================================================================
    # Flink 클러스터 연결 및 일반 설정
    # =================================================================
    sql-gateway.endpoint.rest.address: 0.0.0.0
    sql-gateway.endpoint.rest.port: 8083
    
    jobmanager.rpc.address: flink-busan-cluster-20-rest.flink-busan.svc.cluster.local
    jobmanager.rpc.port: 6123
    taskmanager.numberOfTaskSlots: "16"

    classloader.parent-first-patterns.defaults: 'java.;scala.;org.apache.flink.;org.apache.kafka.;org.apache.hadoop.;software.amazon.;org.apache.iceberg.;org.apache.parquet.'
---
# SQL Gateway Deployment: 실제 SQL Gateway Pod를 실행
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway-20
  namespace: flink-busan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-sql-gateway-20
  template:
    metadata:
      labels:
        app: flink-sql-gateway-20
    spec:
      initContainers:
        # Python 초기화 컨테이너: Flink Python API 설치
        - name: python-init
          image: python:3.10.12-slim
          command:
            - /bin/sh
            - -c
            - |
              pip3 install apache-flink==2.0.1
              
              mkdir -p /python/link/bin
              mkdir -p /python/link/lib
              
              cp -r /usr/local/bin/* /python/link/bin/
              cp -r /usr/local/lib/* /python/link/lib/

          volumeMounts:
            - name: flink-python-bin-volume
              mountPath: /python/link/bin
            - name: flink-python-lib-volume
              mountPath: /python/link/lib
        # Flink 라이브러리 초기화 컨테이너
        - name: flink-lib-init
          image: flink:2.0.1-java17
          command:
            - /bin/sh
            - -c
            - |
              cp -r /opt/flink/lib/* /flink-libs
              rm -rf /flink-libs/flink-shaded-hadoop-2-uber*
              cp -r /opt/flink/plugins/* /flink-plugins
              
              cp -r /usr/local/bin/* /python/link/bin
          volumeMounts:
            - name: flink-lib-volume
              mountPath: /flink-libs
            - name: flink-plugin-volume
              mountPath: /flink-plugins
            - name: flink-python-bin-volume
              mountPath: /python/link/bin
            - name: flink-python-lib-volume
              mountPath: /python/link/lib
        # 의존성 다운로더 컨테이너: 필요한 외부 라이브러리 다운로드
        - name: dependency-downloader
          image: apache/hadoop:3.3.5  # alpine:3.18
          command:
            - /bin/sh
            - -c
            - |

              cp -r /opt/hadoop/* /hadoop

              cd /flink-libs

              # hive Metastore 접근 세팅
              wget https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
              wget https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
              wget https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar

              # JDBC 접근 세팅
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc-core/4.0.0-2.0/flink-connector-jdbc-core-4.0.0-2.0.jar
              wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar
              wget https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.9.4/clickhouse-jdbc-0.9.4.jar

              # 카프카 세팅
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.0-2.0/flink-sql-connector-kafka-4.0.0-2.0.jar
              wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.0/kafka-clients-3.3.0.jar
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-avro/2.0.1/flink-avro-2.0.1.jar
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-avro-confluent-registry/2.0.1/flink-avro-confluent-registry-2.0.1.jar
              wget https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.0.16/kafka-schema-registry-client-7.0.16.jar
              wget https://repo1.maven.org/maven2/org/apache/avro/avro/1.10.2/avro-1.10.2.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.5/jackson-databind-2.13.5.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.5/jackson-core-2.13.5.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.5/jackson-annotations-2.13.5.jar

              mkdir -p /flink-plugins/s3-fs-hadoop

              # iceberg 세팅
              wget -P /flink-plugins/s3-fs-hadoop https://repo1.maven.org/maven2/org/apache/flink/flink-s3-fs-hadoop/2.0.1/flink-s3-fs-hadoop-2.0.1.jar
              wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-flink-runtime-2.0/1.10.0/iceberg-flink-runtime-2.0-1.10.0.jar

              # paimon 세팅
              wget https://repo.maven.apache.org/maven2/org/apache/paimon/paimon-flink-2.0/1.3.0/paimon-flink-2.0-1.3.0.jar

              # MinIO 세팅
              wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.793/aws-java-sdk-bundle-1.12.793.jar

              # hadoop 3.3.5 세팅
              cp /hadoop/share/hadoop/common/hadoop-common-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/commons-configuration2-2.8.0.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/stax2-api-4.2.1.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/commons-logging-1.1.3.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/hadoop-shaded-guava-1.1.1.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/hadoop-auth-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/woodstox-core-5.4.0.jar /flink-libs
              cp /hadoop/share/hadoop/hdfs/hadoop-hdfs-client-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-core-3.3.5.jar /flink-libs
              wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.5/hadoop-aws-3.3.5.jar

          volumeMounts:
            - name: flink-lib-volume
              mountPath: /flink-libs
            - name: flink-plugin-volume
              mountPath: /flink-plugins
            - name: hadoop
              mountPath: /hadoop
      containers:
      # SQL Gateway 메인 컨테이너
      - name: sql-gateway
        env:
          - name: TZ
            value: Asia/Seoul
          - name: HADOOP_HOME
            value: /hadoop
          - name: HADOOP_CLASSPATH
            value: /hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*
        image: flink:2.0.1-java17
        command: ["/opt/flink/bin/sql-gateway.sh", "start-foreground"]
        ports:
        - containerPort: 8083
          name: sql-gateway
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
          - name: hadoop
            mountPath: /hadoop
          - name: flink-python-bin-volume
            mountPath: /usr/local/bin
          - name: flink-python-lib-volume
            mountPath: /usr/local/lib
          - name: flink-lib-volume
            mountPath: /opt/flink/lib
          - name: flink-plugin-volume
            mountPath: /opt/flink/plugins
          - name: sql-gateway-config
            mountPath: /opt/flink/conf/config.yaml
            subPath: config.yaml
      volumes:
        - name: sql-gateway-config
          configMap:
            name: flink-sql-gateway-config-20
        - name: flink-lib-volume
          emptyDir: { }
        - name: flink-plugin-volume
          emptyDir: { }
        - name: flink-python-bin-volume
          emptyDir: { }
        - name: flink-python-lib-volume
          emptyDir: { }
        - name: hadoop
          emptyDir: { }
---
# SQL Gateway Service: 외부에서 접근할 수 있도록 NodePort 타입으로 설정
apiVersion: v1
kind: Service
metadata:
  name: sql-gateway-service-20
  namespace: flink-busan
spec:
  selector:
    app: flink-sql-gateway-20
  ports:
  - name: sql-gateway
    port: 8083
    targetPort: 8083
    nodePort: 30109
  type: NodePort