# Flink 세션 클러스터 배포 설정
# FlinkDeployment 리소스를 사용하여 Flink 세션 클러스터를 생성합니다.
# 세션 클러스터는 여러 작업을 실행할 수 있는 공유 클러스터입니다.

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-busan-cluster
  namespace: flink-busan
spec:
  image: flink:1.18.1-java17
  flinkVersion: v1_18
  flinkConfiguration:
    # 웹 UI에서 작업 취소 및 제출 기능 활성화
    web.cancel.enable: 'true'
    web.submit.enable: "true"
    # TaskManager당 Task Slot 수 설정
    taskmanager.numberOfTaskSlots: "2"
    # 클래스로더 부모 우선 패턴 설정 (의존성 충돌 방지)
    classloader.parent-first-patterns.defaults: 'java.;scala.;org.apache.flink.;org.apache.kafka.;org.apache.hadoop.;software.amazon.;org.apache.iceberg.;org.apache.parquet.'

  serviceAccount: flink-sa
  # JobManager 설정: 클러스터 관리자
  jobManager:
    resource:
      memory: 1G
      cpu: 1
  # TaskManager 설정: 실제 작업을 실행하는 워커 노드
  taskManager:
    replicas: 2
    resource:
      memory: 1G
      cpu: 1
  podTemplate:
    spec:
      initContainers:
        - name: lib-downloader
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /opt/flink/usrlib
              cd /opt/flink/usrlib
              echo "Downloading libraries..."
              wget -q https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.1.2-1.18/flink-connector-jdbc-3.1.2-1.18.jar
              wget -q https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.3.0/mysql-connector-j-8.3.0.jar
              wget -q https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/3.0.1-1.18/flink-connector-kafka-3.0.1-1.18.jar
              wget -q https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.6.1/kafka-clients-3.6.1.jar
              echo "Download complete."
          volumeMounts:
            - name: flink-usrlib
              mountPath: /opt/flink/usrlib
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: flink-usrlib
              mountPath: /opt/flink/usrlib
      volumes:
        - name: flink-usrlib
          emptyDir: {}