# Flink 세션 클러스터 배포 설정
# FlinkDeployment 리소스를 사용하여 Flink 세션 클러스터를 생성합니다.
# 세션 클러스터는 여러 작업을 실행할 수 있는 공유 클러스터입니다.

apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-busan-cluster-20
  namespace: flink-busan
spec:
  image: flink:1.18.1-java17
  flinkVersion: v1_18
  flinkConfiguration:
    # 웹 UI에서 작업 취소 및 제출 기능 활성화
    web.cancel.enable: 'true'
    web.submit.enable: "true"
    # TaskManager당 Task Slot 수 설정
    taskmanager.numberOfTaskSlots: "2"
    # 클래스로더 부모 우선 패턴 설정 (의존성 충돌 방지)
    classloader.parent-first-patterns.defaults: 'java.;scala.;org.apache.flink.;org.apache.kafka.;org.apache.hadoop.;software.amazon.;org.apache.iceberg.;org.apache.parquet.'

  serviceAccount: flink-sa
  # JobManager 설정: 클러스터 관리자
  jobManager:
    resource:
      memory: 2G
      cpu: 1
  # TaskManager 설정: 실제 작업을 실행하는 워커 노드
  taskManager:
    resource:
      memory: 4G
      cpu: 2
  # podTemplate:
  #   spec:
  #     containers:
  #       # 메인 Flink 컨테이너
  #       - name: flink-main-container
  #         env:
  #           - name: TZ
  #             value: Asia/Seoul
  #         volumeMounts:
  #           - name: flink-python-bin-volume
  #             mountPath: /usr/local/bin
  #           - name: flink-python-lib-volume
  #             mountPath: /usr/local/lib
  #     initContainers:
  #       # Python 초기화 컨테이너: Flink Python API 설치
  #       - name: python-init
  #         image: python:3.10.12-slim
  #         command:
  #           - /bin/sh
  #           - -c
  #           - |
  #             pip3 install apache-flink==1.18.1
  #             mkdir -p /python/link/bin
  #             mkdir -p /python/link/lib
  #             cp -r /usr/local/bin/* /python/link/bin/
  #             cp -r /usr/local/lib/* /python/link/lib/
  #         volumeMounts:
  #           - name: flink-python-bin-volume
  #             mountPath: /python/link/bin
  #           - name: flink-python-lib-volume
  #             mountPath: /python/link/lib
  #     volumes:
  #       - name: flink-python-bin-volume
  #         emptyDir: { }
  #       - name: flink-python-lib-volume
  #         emptyDir: { }